//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDataLayout
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discuss
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Discuss()
        {
            this.DiscussContents = new HashSet<DiscussContent>();
        }
    
        public int Id { get; set; }
        public int WorkSpaceId { get; set; }
        public string DiscussName { get; set; }
        public string CreatTime { get; set; }
        public int UserID { get; set; }
        public Nullable<int> WorkSpaceID1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiscussContent> DiscussContents { get; set; }
        public virtual User User { get; set; }
        public virtual WorkSpace WorkSpace { get; set; }
    }
}
