//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDataLayout
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscussContent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DiscussContent()
        {
            this.Important = false;
            this.IsRead = true;
            this.TouchNumber = 0;
            this.DiscussReturns = new HashSet<DiscussReturn>();
            this.DiscussAttaches = new HashSet<DiscussAttach>();
        }
    
        public int Id { get; set; }
        public int DiscussId { get; set; }
        public string DiscussType { get; set; }
        public bool Important { get; set; }
        public bool IsRead { get; set; }
        public string CreatTime { get; set; }
        public byte[] Icon { get; set; }
        public string Title { get; set; }
        public int DiscussUserId { get; set; }
        public string Content { get; set; }
        public int TouchNumber { get; set; }
    
        public virtual Discuss Discuss { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiscussReturn> DiscussReturns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiscussAttach> DiscussAttaches { get; set; }
    }
}
