//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDataLayout
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscussReturn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DiscussReturn()
        {
            this.DiscussAttaches = new HashSet<DiscussAttach>();
        }
    
        public int Id { get; set; }
        public int DiscussContentId { get; set; }
        public int DiscussUserId { get; set; }
        public string ReturnContent { get; set; }
        public string ReturnTime { get; set; }
    
        public virtual DiscussContent DiscussContent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiscussAttach> DiscussAttaches { get; set; }
    }
}
