//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDataLayout
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocLocation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocLocation()
        {
            this.DocComents = new HashSet<DocComent>();
        }
    
        public int ID { get; set; }
        public int DocumentManageID { get; set; }
        public string VisualScope { get; set; }
        public int DocReaderId { get; set; }
        public Nullable<int> DocSenderId { get; set; }
        public bool IsRuleTransaction { get; set; }
    
        public virtual DocumentManage DocumentManage { get; set; }
        public virtual DocReader DocReader { get; set; }
        public virtual DocSender DocSender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocComent> DocComents { get; set; }
    }
}
