//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDataLayout
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventTime
    {
        public int Id { get; set; }
        public string TimePoint { get; set; }
        public string SpacePoint { get; set; }
        public string EventName { get; set; }
        public string EventType { get; set; }
        public string District { get; set; }
        public Nullable<int> LoginLogID { get; set; }
    
        public virtual LoginLog LoginLog { get; set; }
    }
}
