//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDataLayout
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeoGraph
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Content { get; set; }
        public string GeometryType { get; set; }
        public string Geometry { get; set; }
        public string Geogrphy { get; set; }
        public string Points { get; set; }
        public string Point3D { get; set; }
    }
}
