//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDataLayout
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectChangeEvent
    {
        public int Id { get; set; }
        public int ProjectID { get; set; }
        public string Cause { get; set; }
        public string FielName { get; set; }
        public string Value { get; set; }
        public string Changer { get; set; }
        public System.DateTime ChangeTime { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
