//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDataLayout
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tudi_ApproveInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tudi_ApproveInfo()
        {
            this.Tudi_Approve_PlotInfo = new HashSet<Tudi_Approve_PlotInfo>();
        }
    
        public int Id { get; set; }
        public int Tudi_projInfoId { get; set; }
        public string Proj_no { get; set; }
        public string Proj_name { get; set; }
        public string Receivtime { get; set; }
        public string Xmstate { get; set; }
        public int Tudi_handleStateId { get; set; }
        public string Chargerarea { get; set; }
        public string Notetime { get; set; }
        public string Chargevalue { get; set; }
        public string Responsetime { get; set; }
        public string ResponseNo { get; set; }
        public string Responsarea { get; set; }
        public string Fram_tot { get; set; }
        public string Fram_state { get; set; }
        public string Fram_group { get; set; }
        public string Tilth_state { get; set; }
        public string Tilth_group { get; set; }
        public string BF_group { get; set; }
        public string Build_tot { get; set; }
        public string Build_group { get; set; }
        public string Build_state { get; set; }
        public string Unused_tot { get; set; }
        public string Unused_Group { get; set; }
        public string Unused_state { get; set; }
        public string Pay_std { get; set; }
        public string Reset_farmer { get; set; }
        public string Labour_force { get; set; }
        public string Pay_way { get; set; }
        public string check_Area { get; set; }
        public string Chk_Tilth_Area { get; set; }
        public string Responsefile { get; set; }
    
        public virtual Tudi_projInfo Tudi_projInfo { get; set; }
        public virtual Tudi_handleState Tudi_handleState { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tudi_Approve_PlotInfo> Tudi_Approve_PlotInfo { get; set; }
    }
}
