using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BCP.ViewModel
{
    /// <summary>
    /// BussnessVer DTO
    /// </summary>
    public partial class BussnessVerDTO
    {
        public System.Int32 ID { get; set; }
        public System.String Name { get; set; }
        public System.String other { get; set; }
    }
}

