using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BCP.ViewModel
{
    /// <summary>
    /// CustomerGoup DTO
    /// </summary>
    public partial class CustomerGoupDTO
    {
        public System.Int32 ID { get; set; }
        public System.String GroupName { get; set; }
        public System.Int32 CreatID { get; set; }
        public System.Int64 EventTime { get; set; }
    }
}

