using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BCP.ViewModel
{
    /// <summary>
    /// WorkSpaceType DTO
    /// </summary>
    public partial class WorkSpaceTypeDTO
    {
        public System.Int32 Id { get; set; }
        public System.String ByProperty { get; set; }
        public System.Int64 EventTime { get; set; }
    }
}

