//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.Domain.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetBaseType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssetBaseType()
        {
            this.AssetTypes = new HashSet<AssetBaseType>();
            this.OrganizationAssetTypes = new HashSet<OrganizationAssetType>();
        }
    
        public int Id { get; set; }
        public string TypeName { get; set; }
        public string Note { get; set; }
        public int OrganizationID { get; set; }
        public Nullable<int> AssetTypeId { get; set; }
        public long EventTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssetBaseType> AssetTypes { get; set; }
        public virtual AssetBaseType AssetType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrganizationAssetType> OrganizationAssetTypes { get; set; }
    }
}
