//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.Domain.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authorization
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Authorization()
        {
            this.WorkMessages = new HashSet<WorkMessage>();
        }
    
        public int Id { get; set; }
        public Nullable<int> PostID { get; set; }
        public string PropertyValue { get; set; }
        public string PostRelation { get; set; }
        public Nullable<int> PostID1 { get; set; }
        public Nullable<int> ModulPropertyId { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> UserID1 { get; set; }
        public long EventTime { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual Post Post1 { get; set; }
        public virtual ModulProperty ModulProperty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkMessage> WorkMessages { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
