//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.Domain.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomGeographicType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomGeographicType()
        {
            this.CustomGeographicTypes = new HashSet<CustomGeographicType>();
            this.DesktopGeoManages = new HashSet<DesktopGeoManage>();
        }
    
        public int ID { get; set; }
        public string TypeName { get; set; }
        public string Descript { get; set; }
        public Nullable<int> CustomGeographicTypeID { get; set; }
        public Nullable<int> EventTimeEventTimeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomGeographicType> CustomGeographicTypes { get; set; }
        public virtual CustomGeographicType CustomGeographicType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DesktopGeoManage> DesktopGeoManages { get; set; }
    }
}
