//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.Domain.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class DllFileStream
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DllFileStream()
        {
            this.DllFileStreams = new HashSet<DllFileStream>();
            this.WorkModuls = new HashSet<WorkModul>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IndustrySolutionId { get; set; }
        public Nullable<int> DllFileStreamID { get; set; }
        public string Model { get; set; }
        public byte[] DllfileStream { get; set; }
        public string FileName { get; set; }
        public Nullable<bool> MainWindowName { get; set; }
        public string Txt2 { get; set; }
        public string URI { get; set; }
        public string Paragram { get; set; }
        public long EventTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DllFileStream> DllFileStreams { get; set; }
        public virtual DllFileStream DllFileStream1 { get; set; }
        public virtual IndustrySolution IndustrySolution { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkModul> WorkModuls { get; set; }
    }
}
