//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.Domain.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentManage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocumentManage()
        {
            this.DocTypes = new HashSet<DocType>();
            this.workTasks = new HashSet<workTask>();
            this.DocumentContents = new HashSet<DocumentContent>();
            this.CustomTabDatas = new HashSet<CustomTabData>();
            this.DocLocations = new HashSet<DocLocation>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Doctype { get; set; }
        public string Content { get; set; }
        public string URL { get; set; }
        public string FileNumber { get; set; }
        public Nullable<int> DocCheckStateID { get; set; }
        public Nullable<int> SecurityinfoID { get; set; }
        public Nullable<int> WorkSpaceBaseTypeId { get; set; }
        public long EventTime { get; set; }
        public Nullable<int> DocManageStateID { get; set; }
    
        public virtual DocCheckState DocHanderState { get; set; }
        public virtual Securityinfo Securityinfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocType> DocTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<workTask> workTasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentContent> DocumentContents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomTabData> CustomTabDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocLocation> DocLocations { get; set; }
        public virtual WorkSpaceBaseType WorkSpaceBaseType { get; set; }
        public virtual DocManageState DocManageState { get; set; }
    }
}
