//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.Domain.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentContent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocumentContent()
        {
            this.DocumentContents = new HashSet<DocumentContent>();
        }
    
        public int ID { get; set; }
        public string Content { get; set; }
        public string Message { get; set; }
        public Nullable<int> DocumentManageID { get; set; }
        public Nullable<int> DocumentContentID { get; set; }
        public Nullable<int> workTaskId { get; set; }
        public long EventTime { get; set; }
    
        public virtual DocumentManage DocumentManage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentContent> DocumentContents { get; set; }
        public virtual DocumentContent DocumentContent1 { get; set; }
        public virtual workTask workTask { get; set; }
    }
}
