//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.Domain.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndustrySolution
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IndustrySolution()
        {
            this.WorkSpaces = new HashSet<WorkSpace>();
            this.DllFileStreams = new HashSet<DllFileStream>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IndustryCodeID { get; set; }
        public string Name { get; set; }
        public string Content { get; set; }
        public string Note { get; set; }
        public long EventTime { get; set; }
    
        public virtual IndustryCode IndustryCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkSpace> WorkSpaces { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DllFileStream> DllFileStreams { get; set; }
    }
}
