//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.Domain.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizBasic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrganizBasic()
        {
            this.OrganicInvestors = new HashSet<OrganicInvestor>();
            this.OrgaRegisterDocments = new HashSet<OrgaRegisterDocment>();
            this.OrganizBasics = new HashSet<OrganizBasic>();
            this.Organization_ContacTable = new HashSet<Organization_ContacTable>();
            this.OrganicInvestors1 = new HashSet<OrganicInvestor>();
            this.Products = new HashSet<Product>();
        }
    
        public int ID { get; set; }
        public string RegistrationNumber { get; set; }
        public string Domicile { get; set; }
        public Nullable<int> LegaPersonID { get; set; }
        public string BussinessAddress { get; set; }
        public string BussinessAddressDetail { get; set; }
        public string RegisteredCapital { get; set; }
        public string BusinessScope { get; set; }
        public string BussinessModel { get; set; }
        public Nullable<int> SubordinateID { get; set; }
        public int Organization_TypeID { get; set; }
        public string SupervisorSection { get; set; }
        public string OperatingPeriod { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public string OtherInfo { get; set; }
        public Nullable<int> OverrideParent { get; set; }
        public int OrganizationID { get; set; }
        public int IndustryCodeID { get; set; }
        public int AdministrativecodeSacID { get; set; }
        public bool IsValid { get; set; }
        public long EventTime { get; set; }
    
        public virtual Subordinate Subordinate { get; set; }
        public virtual Organization_Type Organization_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrganicInvestor> OrganicInvestors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrgaRegisterDocment> OrgaRegisterDocments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrganizBasic> OrganizBasics { get; set; }
        public virtual OrganizBasic OrganizBasic1 { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual IndustryCode IndustryCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Organization_ContacTable> Organization_ContacTable { get; set; }
        public virtual Administrativecode Administrativecode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrganicInvestor> OrganicInvestors1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}
