//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.Domain.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationAssetType
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Note { get; set; }
        public Nullable<int> physicalAssetId { get; set; }
        public int AssetBaseTypeId { get; set; }
        public long EventTime { get; set; }
    
        public virtual physicalAsset physicalAsset { get; set; }
        public virtual AssetBaseType AssetBaseType { get; set; }
    }
}
