//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.Domain.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Position()
        {
            this.IsAdministrator = false;
            this.Positions = new HashSet<Position>();
            this.Employees = new HashSet<Employee>();
            this.Posts = new HashSet<Post>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public bool IsValid { get; set; }
        public string PositionType { get; set; }
        public string PositionTile { get; set; }
        public string TaskNature { get; set; }
        public string WorkLocation { get; set; }
        public string SolaryStandard { get; set; }
        public Nullable<int> PositionID { get; set; }
        public int OrganizationID { get; set; }
        public bool IsAdministrator { get; set; }
        public Nullable<int> PostRequireID { get; set; }
        public string PositionLevel { get; set; }
        public long EventTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Position> Positions { get; set; }
        public virtual Position Position1 { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual PostRequire PostRequire { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Post> Posts { get; set; }
    }
}
