//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.Domain.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductCompositions1 = new HashSet<ProductComposition>();
            this.ProductCustomTypes = new HashSet<ProductCustomType>();
            this.ProductEvents = new HashSet<ProductEvent>();
            this.physicalAssets = new HashSet<physicalAsset>();
        }
    
        public int Id { get; set; }
        public int ProductStandardID { get; set; }
        public string Pname { get; set; }
        public string PModel { get; set; }
        public string Units { get; set; }
        public string SCode { get; set; }
        public string FCode { get; set; }
        public string PCode { get; set; }
        public Nullable<int> OrganizBasicID { get; set; }
        public Nullable<int> OrganizationID { get; set; }
        public long EventTime { get; set; }
    
        public virtual ProductStandard ProductStandard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductComposition> ProductCompositions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCustomType> ProductCustomTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductEvent> ProductEvents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<physicalAsset> physicalAssets { get; set; }
        public virtual OrganizBasic OrganizBasic { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
