//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.Domain.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductComposition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductComposition()
        {
            this.ProductCompositions = new HashSet<ProductComposition>();
        }
    
        public int Id { get; set; }
        public int ChildProductId { get; set; }
        public string Function { get; set; }
        public string descript { get; set; }
        public string Value { get; set; }
        public int ProductCompositionId { get; set; }
        public long EventTime { get; set; }
    
        public virtual Product Product1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductComposition> ProductCompositions { get; set; }
        public virtual ProductComposition ProductComposition1 { get; set; }
    }
}
