//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.Domain.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductStandard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductStandard()
        {
            this.ProductStandards = new HashSet<ProductStandard>();
            this.Products = new HashSet<Product>();
        }
    
        public int ID { get; set; }
        public string ProductCode { get; set; }
        public string Name { get; set; }
        public string Descript { get; set; }
        public Nullable<int> Parent { get; set; }
        public string measureUnit { get; set; }
        public string ParentCode { get; set; }
        public string Vesion { get; set; }
        public long EventTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductStandard> ProductStandards { get; set; }
        public virtual ProductStandard ProductStandard1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}
