//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.Domain.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductEvent
    {
        public int Id { get; set; }
        public string EventName { get; set; }
        public string Content { get; set; }
        public System.DateTime EventTime { get; set; }
        public int ProductId { get; set; }
        public int Creater { get; set; }
        public long EventTime1 { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
