//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.Domain.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Securityinfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Securityinfo()
        {
            this.DocumentManages = new HashSet<DocumentManage>();
            this.Securityinfoes = new HashSet<Securityinfo>();
        }
    
        public int ID { get; set; }
        public string SecurityName { get; set; }
        public int Level { get; set; }
        public string Descript { get; set; }
        public Nullable<int> SecurityinfoID { get; set; }
        public long EventTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentManage> DocumentManages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Securityinfo> Securityinfoes { get; set; }
        public virtual Securityinfo Securityinfo1 { get; set; }
    }
}
