//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.Domain.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserGroup()
        {
            this.MessageGroupMessagers = new HashSet<MessageGroupMessager>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Creator { get; set; }
        public int UserID { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string State { get; set; }
        public int GroupNameID { get; set; }
        public string Rule { get; set; }
        public long EventTime { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MessageGroupMessager> MessageGroupMessagers { get; set; }
        public virtual GroupName GroupName { get; set; }
    }
}
