//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.Domain.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRelateTable
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int UserID1 { get; set; }
        public int UserRelateTypeID { get; set; }
        public string RelateObject { get; set; }
        public string Notes { get; set; }
        public long EventTime { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual UserRelateType UserRelateType { get; set; }
    }
}
