//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.Domain.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkSpace
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkSpace()
        {
            this.WorkSpaces = new HashSet<WorkSpace>();
            this.WorkSpaceRoles = new HashSet<WorkSpaceRole>();
            this.DocReaders = new HashSet<DocReader>();
            this.WorkSpaceTypes = new HashSet<WorkSpaceType>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Content { get; set; }
        public string MarkerString { get; set; }
        public string Comment { get; set; }
        public bool IsValid { get; set; }
        public string Descript { get; set; }
        public Nullable<int> IndustrySolutionId { get; set; }
        public Nullable<int> WorkSpaceID { get; set; }
        public Nullable<int> WorkModulId { get; set; }
        public long EventTime { get; set; }
    
        public virtual IndustrySolution IndustrySolution { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkSpace> WorkSpaces { get; set; }
        public virtual WorkSpace WorkSpace1 { get; set; }
        public virtual WorkModul WorkModul { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkSpaceRole> WorkSpaceRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocReader> DocReaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkSpaceType> WorkSpaceTypes { get; set; }
    }
}
