//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.Domain.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkSpaceRole
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public int WorkSpaceID { get; set; }
        public int OrganizationID { get; set; }
        public string Descript { get; set; }
        public Nullable<int> WorkModulId { get; set; }
        public Nullable<int> UserID { get; set; }
        public long EventTime { get; set; }
    
        public virtual WorkSpace WorkSpace { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual WorkModul WorkModul { get; set; }
        public virtual User User { get; set; }
    }
}
