//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDataLayout
{
    using System;
    using System.Collections.Generic;
    
    public partial class GBT_13923_2006
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GBT_13923_2006()
        {
            this.GBT_13923_20061 = new HashSet<GBT_13923_2006>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public string FeatureName { get; set; }
        public Nullable<bool> t5_2K { get; set; }
        public Nullable<bool> K5_100K { get; set; }
        public Nullable<bool> K25_M { get; set; }
        public Nullable<int> Parent { get; set; }
        public int BussnessVerID { get; set; }
        public string Extend { get; set; }
        public string Descript { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GBT_13923_2006> GBT_13923_20061 { get; set; }
        public virtual GBT_13923_2006 GBT_13923_20062 { get; set; }
        public virtual BussnessVer BussnessVer { get; set; }
    }
}
