//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDataLayout
{
    using System;
    using System.Collections.Generic;
    
    public partial class Land_Graph
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Land_Graph()
        {
            this.Land_manager = new HashSet<Land_manager>();
            this.DesktopGeoManages = new HashSet<DesktopGeoManage>();
            this.Tudi_plotInfo = new HashSet<Tudi_plotInfo>();
        }
    
        public int ID { get; set; }
        public System.Data.Entity.Spatial.DbGeometry Geometry { get; set; }
        public string Area { get; set; }
        public System.Data.Entity.Spatial.DbGeography geography { get; set; }
        public string Points { get; set; }
        public string X3DPoints { get; set; }
        public string CoordinarySystem { get; set; }
        public string SourcesTable { get; set; }
        public string SourcesID { get; set; }
        public string GeometryType { get; set; }
        public string GraphName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Land_manager> Land_manager { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DesktopGeoManage> DesktopGeoManages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tudi_plotInfo> Tudi_plotInfo { get; set; }
    }
}
