//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDataLayout
{
    using System;
    using System.Collections.Generic;
    
    public partial class Land_manager
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Land_manager()
        {
            this.Land_Image = new HashSet<Land_Image>();
            this.Land_Ownership = new HashSet<Land_Ownership>();
            this.Land_DemolitionContract = new HashSet<Land_DemolitionContract>();
            this.Land_Video = new HashSet<Land_Video>();
            this.Land_Graph_Handle = new HashSet<Land_Graph_Handle>();
        }
    
        public int ID { get; set; }
        public int Geo_GraphID { get; set; }
        public int Land_TypeID { get; set; }
        public Nullable<int> Land_Item { get; set; }
        public LandState HanderState { get; set; }
        public int StandardadministrativecodeSacID { get; set; }
        public int BussnessVerID { get; set; }
        public Nullable<int> ProjectID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Land_Image> Land_Image { get; set; }
        public virtual Land_Graph Geo_Graph { get; set; }
        public virtual Land_Type Land_Type { get; set; }
        public virtual Land_Type Land_ItemD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Land_Ownership> Land_Ownership { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Land_DemolitionContract> Land_DemolitionContract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Land_Video> Land_Video { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Land_Graph_Handle> Land_Graph_Handle { get; set; }
        public virtual Administrativecode Administrativecode { get; set; }
        public virtual BussnessVer BussnessVer { get; set; }
        public virtual Project Project { get; set; }
    }
}
