//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDataLayout
{
    using System;
    using System.Collections.Generic;
    
    public partial class Land_Ownership
    {
        public int ID { get; set; }
        public string OwnerName { get; set; }
        public string Type { get; set; }
        public string Certificate { get; set; }
        public string Note { get; set; }
        public string Situation { get; set; }
        public string Attitude { get; set; }
        public int Land_managerID { get; set; }
    
        public virtual Land_manager Land_manager { get; set; }
    }
}
