//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDataLayout
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseContext : DbContext
    {
        public DatabaseContext()
            : base("name=DatabaseContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Organization> Organizations { get; set; }
        public virtual DbSet<Organization_ContacTable> Organization_ContactTables { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<User_ContacTable> User_ContactTable { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<LoginLog> LoginLogs { get; set; }
        public virtual DbSet<Land_Graph> Land_Graphs { get; set; }
        public virtual DbSet<Land_Type> Land_Types { get; set; }
        public virtual DbSet<Land_Image> Land_Image { get; set; }
        public virtual DbSet<Land_Video> Land_Video { get; set; }
        public virtual DbSet<IncurredExpense> IncurredExpenses { get; set; }
        public virtual DbSet<Project_Expense> Project_Expense { get; set; }
        public virtual DbSet<Land_DemolitionContract> Land_DemolitionContracts { get; set; }
        public virtual DbSet<OrganizationTransition> OrganizationTransitions { get; set; }
        public virtual DbSet<Land_Graph_Handle> Land_Graph_Handles { get; set; }
        public virtual DbSet<Land_Ownership> Land_Ownerships { get; set; }
        public virtual DbSet<TaskEquipment> TaskEquipments { get; set; }
        public virtual DbSet<Organization_Type> Organization_Type { get; set; }
        public virtual DbSet<DocumentManage> DocumentManages { get; set; }
        public virtual DbSet<UserMessage> UserMessages { get; set; }
        public virtual DbSet<UserGroup> UserGroups { get; set; }
        public virtual DbSet<OrganizationOtherName> OrganizationOtherNames { get; set; }
        public virtual DbSet<Land_TaskType> Land_TaskType { get; set; }
        public virtual DbSet<TaskState> TaskStates { get; set; }
        public virtual DbSet<Land_manager> Land_manager { get; set; }
        public virtual DbSet<Administrativecode> Administrativecodes { get; set; }
        public virtual DbSet<DocumentType> DocumentTypes { get; set; }
        public virtual DbSet<DocManageState> DocManageStates { get; set; }
        public virtual DbSet<BussnessVer> BussnessVers { get; set; }
        public virtual DbSet<TaskItem> TaskItems { get; set; }
        public virtual DbSet<ProductStandard> ProductStandards { get; set; }
        public virtual DbSet<IndustryCode> IndustryCodes { get; set; }
        public virtual DbSet<ZipCode> ZipCodes { get; set; }
        public virtual DbSet<IPCode> IPCodes { get; set; }
        public virtual DbSet<OrganizBasic> OrganizBasics { get; set; }
        public virtual DbSet<PostRequire> PostRequires { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<WorkSpace> WorkSpaces { get; set; }
        public virtual DbSet<Subordinate> Subordinates { get; set; }
        public virtual DbSet<Specialized> Specializeds { get; set; }
        public virtual DbSet<UserRelateTable> UserRelateTables { get; set; }
        public virtual DbSet<UserRelateType> UserRelateTypes { get; set; }
        public virtual DbSet<GBT_13923_2006> GBT_13923_2006s { get; set; }
        public virtual DbSet<ProjectLocation> ProjectLocations { get; set; }
        public virtual DbSet<DocumentContent> DocumentContents { get; set; }
        public virtual DbSet<DocCheckState> DocCheckStates { get; set; }
        public virtual DbSet<Securityinfo> Securityinfoes { get; set; }
        public virtual DbSet<OrganicInvestor> OrganicInvestors { get; set; }
        public virtual DbSet<OrgaRegisterDocment> OrgaRegisterDocments { get; set; }
        public virtual DbSet<RegisterDocumentType> RegisterDocumentTypes { get; set; }
        public virtual DbSet<OrganizationEvent> OrganizationEvents { get; set; }
        public virtual DbSet<MessageGroupMessager> MessageGroupMessagers { get; set; }
        public virtual DbSet<GroupName> GroupNames { get; set; }
        public virtual DbSet<CustomerGoup> CustomerGoups { get; set; }
        public virtual DbSet<DllFileStream> DllFileStreams { get; set; }
        public virtual DbSet<F_Currency> F_Currency { get; set; }
        public virtual DbSet<F_unitgroup> F_unitgroup { get; set; }
        public virtual DbSet<F_measureunit> F_measureunit { get; set; }
        public virtual DbSet<F_account> F_account { get; set; }
        public virtual DbSet<F_itemclass> F_itemclass { get; set; }
        public virtual DbSet<F_item> F_item { get; set; }
        public virtual DbSet<FinaceAccoutTab> FinaceAccoutTabs { get; set; }
        public virtual DbSet<OrganizationCustomType> OrganizationCustomTypes { get; set; }
        public virtual DbSet<CustomCategory> CustomCategories { get; set; }
        public virtual DbSet<DesktopGeoManage> DesktopGeoManages { get; set; }
        public virtual DbSet<CustomGeographicType> CustomGeographicTypes { get; set; }
        public virtual DbSet<TaskLink> TaskLinks { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductEvent> ProductEvents { get; set; }
        public virtual DbSet<ProductComposition> ProductCompositions { get; set; }
        public virtual DbSet<ProductCustomType> ProductCustomTypes { get; set; }
        public virtual DbSet<ProductCustomCategory> ProductCustomCategories { get; set; }
        public virtual DbSet<physicalAsset> physicalAssets { get; set; }
        public virtual DbSet<AssetUse> AssetUses { get; set; }
        public virtual DbSet<AssetMaintenance> AssetMaintenances { get; set; }
        public virtual DbSet<AssetBaseType> AssetBaseTypes { get; set; }
        public virtual DbSet<ProjectChangeEvent> ProjectChangeEvents { get; set; }
        public virtual DbSet<Tudi_spqx> Tudi_spqx { get; set; }
        public virtual DbSet<Tudi_ywlc> Tudi_ywlc { get; set; }
        public virtual DbSet<Tudi_ydjh> Tudi_ydjh { get; set; }
        public virtual DbSet<Tudi_sjydbbjhfl> Tudi_sjydbbjhfl { get; set; }
        public virtual DbSet<Tudi_TaskTypeCode> Tudi_TaskTypeCode { get; set; }
        public virtual DbSet<Tudi_gtgl_TaskCode> Tudi_gtgl_TaskCode { get; set; }
        public virtual DbSet<Tudi_projInfo> Tudi_projInfo { get; set; }
        public virtual DbSet<Tudi_plotInfo> Tudi_plotInfo { get; set; }
        public virtual DbSet<Tudi_projType> Tudi_projType { get; set; }
        public virtual DbSet<Tudi_shenpiState> Tudi_shenpiState { get; set; }
        public virtual DbSet<Tudi_shenpiqx> Tudi_shenpiqx { get; set; }
        public virtual DbSet<Tudi_dikuaiyongtu> Tudi_dikuaiyongtu { get; set; }
        public virtual DbSet<Tudi_projKind> Tudi_projKind { get; set; }
        public virtual DbSet<Tudi_handleState> Tudi_handleState { get; set; }
        public virtual DbSet<Tudi_ApproveInfo> Tudi_ApproveInfo { get; set; }
        public virtual DbSet<Tudi_st_approveInfo> Tudi_st_approveInfo { get; set; }
        public virtual DbSet<Tudi_stph_ApproveInfo> Tudi_stph_ApproveInfo { get; set; }
        public virtual DbSet<Tudi_HandleStep_State> Tudi_HandleStep_State { get; set; }
        public virtual DbSet<Tudi_Approve_PlotInfo> Tudi_Approve_PlotInfo { get; set; }
        public virtual DbSet<OrganizationAssetType> OrganizationAssetTypes { get; set; }
        public virtual DbSet<GeoGraph> GeoGraphs { get; set; }
        public virtual DbSet<Employee> Employees1 { get; set; }
        public virtual DbSet<IndustrySolution> IndustrySolutions { get; set; }
        public virtual DbSet<WorkModul> WorkModuls { get; set; }
        public virtual DbSet<WorkSpaceRole> WorkSpaceRoles { get; set; }
        public virtual DbSet<Authorization> Authorizations { get; set; }
        public virtual DbSet<ModulProperty> ModulProperties { get; set; }
        public virtual DbSet<WorkMessage> WorkMessages { get; set; }
        public virtual DbSet<DocType> DocTypes { get; set; }
        public virtual DbSet<DocReader> DocReaders { get; set; }
        public virtual DbSet<DocSender> DocSenders { get; set; }
        public virtual DbSet<DocComent> DocComents { get; set; }
        public virtual DbSet<JobChange> JobChanges { get; set; }
        public virtual DbSet<WorkSpaceType> WorkSpaceTypes { get; set; }
        public virtual DbSet<WorkInstanceType> WorkInstanceTypes { get; set; }
        public virtual DbSet<workTask> workTasks { get; set; }
        public virtual DbSet<CustomTable> CustomTables { get; set; }
        public virtual DbSet<CustomTabData> CustomTabDatas { get; set; }
        public virtual DbSet<DocLocation> DocLocations { get; set; }
        public virtual DbSet<WorkSpaceBaseType> WorkSpaceBaseTypes { get; set; }
    }
}
