//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDataLayout
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tudi_gtgl_TaskCode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tudi_gtgl_TaskCode()
        {
            this.Tudi_sjydbbjhfl = new HashSet<Tudi_sjydbbjhfl>();
        }
    
        public int Id { get; set; }
        public int AdministrativecodeSacID { get; set; }
        public int TypeCode { get; set; }
        public string xzjb { get; set; }
        public Nullable<int> SubordinateID { get; set; }
    
        public virtual Tudi_TaskTypeCode gtgl_TaskType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tudi_sjydbbjhfl> Tudi_sjydbbjhfl { get; set; }
        public virtual Subordinate Subordinate { get; set; }
        public virtual Administrativecode Administrativecode { get; set; }
    }
}
