//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDataLayout
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tudi_ydjh
    {
        public int Id { get; set; }
        public string TypeName { get; set; }
        public string Content { get; set; }
        public string exchangecontent { get; set; }
        public string exchangeFormat { get; set; }
        public int Tudi_spqxId { get; set; }
        public int Tudi_ywlcId { get; set; }
        public int Tudi_sjydbbjhflId { get; set; }
    
        public virtual Tudi_spqx Tudi_spqx { get; set; }
        public virtual Tudi_ywlc Tudi_ywlc { get; set; }
        public virtual Tudi_sjydbbjhfl Tudi_sjydbbjhfl { get; set; }
    }
}
