//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDataLayout
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tudi_projInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tudi_projInfo()
        {
            this.Tudi_ApproveInfo = new HashSet<Tudi_ApproveInfo>();
            this.Tudi_st_approveInfo = new HashSet<Tudi_st_approveInfo>();
            this.Tudi_stph_ApproveInfo = new HashSet<Tudi_stph_ApproveInfo>();
            this.Tudi_plotInfo = new HashSet<Tudi_plotInfo>();
        }
    
        public int Id { get; set; }
        public int ProjectID { get; set; }
        public string proj_no { get; set; }
        public string proj_name { get; set; }
        public string canton_code { get; set; }
        public int Tudi_projTypeId { get; set; }
        public string accept_date { get; set; }
        public int Tudi_projKindId { get; set; }
        public string Farm_Tot { get; set; }
        public string Farm_State { get; set; }
        public string Farm_Group { get; set; }
        public string Tilth_State { get; set; }
        public string Tilth_Group { get; set; }
        public string BF_Group { get; set; }
        public string Build_Tot { get; set; }
        public string Build_Group { get; set; }
        public string Build_State { get; set; }
        public string UnUsed_Tot { get; set; }
        public string UnUsed_Group { get; set; }
        public string UnUsed_State { get; set; }
        public string Pay_std { get; set; }
        public string Reset_Farmer { get; set; }
        public string Labour_Force { get; set; }
        public string put_way { get; set; }
        public string approve_state { get; set; }
        public int Tudi_shenpiStateId { get; set; }
        public int Tudi_Approve_type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tudi_ApproveInfo> Tudi_ApproveInfo { get; set; }
        public virtual Project Project { get; set; }
        public virtual Tudi_projType Tudi_projType { get; set; }
        public virtual Tudi_projKind Tudi_projKind { get; set; }
        public virtual Tudi_shenpiqx Tudi_shenpiqx { get; set; }
        public virtual Tudi_shenpiState Tudi_shenpiState { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tudi_st_approveInfo> Tudi_st_approveInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tudi_stph_ApproveInfo> Tudi_stph_ApproveInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tudi_plotInfo> Tudi_plotInfo { get; set; }
    }
}
