//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDataLayout
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tudi_st_approveInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tudi_st_approveInfo()
        {
            this.Tudi_st_approveInfo1 = new HashSet<Tudi_st_approveInfo>();
            this.Tudi_Approve_PlotInfo = new HashSet<Tudi_Approve_PlotInfo>();
        }
    
        public int Id { get; set; }
        public string Proj_no { get; set; }
        public string Approve_notion { get; set; }
        public string Fram_tot { get; set; }
        public string Fram_state { get; set; }
        public string Fram_group { get; set; }
        public string Tilth_State { get; set; }
        public string Tilth_group { get; set; }
        public string BF_group { get; set; }
        public string Build_tot { get; set; }
        public string Build_state { get; set; }
        public string Build_group { get; set; }
        public string Unused_tot { get; set; }
        public string Unused_state { get; set; }
        public string Unuserd_group { get; set; }
        public string Pay_std { get; set; }
        public string Reset_farmer { get; set; }
        public string Labour_force { get; set; }
        public string Pay_way { get; set; }
        public string Check_Area { get; set; }
        public string Chk_Tilth_Area { get; set; }
        public string Approve_state { get; set; }
        public string Approve_type { get; set; }
        public int Tudi_shenpiqxId { get; set; }
        public int Tudi_shenpiStateId { get; set; }
        public int Tudi_projInfoId { get; set; }
        public Nullable<int> Tudi_st_approveInfoId { get; set; }
    
        public virtual Tudi_shenpiqx Tudi_shenpiqx { get; set; }
        public virtual Tudi_shenpiState Tudi_shenpiState { get; set; }
        public virtual Tudi_projInfo Tudi_projInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tudi_st_approveInfo> Tudi_st_approveInfo1 { get; set; }
        public virtual Tudi_st_approveInfo Tudi_st_approveInfo2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tudi_Approve_PlotInfo> Tudi_Approve_PlotInfo { get; set; }
    }
}
