//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDataLayout
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tudi_plotInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tudi_plotInfo()
        {
            this.Tudi_Approve_PlotInfo = new HashSet<Tudi_Approve_PlotInfo>();
        }
    
        public int Id { get; set; }
        public string proj_no { get; set; }
        public string Plotid { get; set; }
        public string plotname { get; set; }
        public string total_area { get; set; }
        public Nullable<int> Geo_GraphID { get; set; }
        public int Tudi_dikuaiyongtuId { get; set; }
        public int Tudi_projInfoId { get; set; }
    
        public virtual Land_Graph Geo_Graph { get; set; }
        public virtual Tudi_dikuaiyongtu Tudi_dikuaiyongtu { get; set; }
        public virtual Tudi_projInfo Tudi_projInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tudi_Approve_PlotInfo> Tudi_Approve_PlotInfo { get; set; }
    }
}
